// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xavomawrcjzqucvbldms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhdm9tYXdyY2p6cXVjdmJsZG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mjg4MzEsImV4cCI6MjA3MzQwNDgzMX0.6vE-qlBl4tx3ILXxIsUjxFxMGAlrk6OVO-_bSr8XPKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});